//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSOL.EktronCms.ContentMaker.Samples {
    
    
    public partial class ContentRenderSamples {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// wRendererForDynamicItem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WSOL.ObjectRenderer.WebControls.ObjectRenderer wRendererForDynamicItem;
        
        /// <summary>
        /// wRendererForArticles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WSOL.ObjectRenderer.WebControls.ObjectRenderer wRendererForArticles;
        
        /// <summary>
        /// wRendererForMixed control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WSOL.ObjectRenderer.WebControls.ObjectRenderer wRendererForMixed;
    }
}
