// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>WSOL.Custom.ContentTypes.CalendarEvent</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace WSOL.Custom.ContentMaker.Samples.ContentTypes.CalendarEvent
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class root
    {

        private System.DateTime startTimeField;

        private System.DateTime endTimeField;

        private System.DateTime durationField;

        private string displayTitleField;

        private string locationField;

        private string isAllDayField;

        private string descriptionField;

        private rootRecurrence recurrenceField;

        private string isVarianceField;

        private string isCancelledField;

        private System.DateTime originalStartField;

        private string originalTimeZoneField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime StartTime
        {
            get
            {
                return this.startTimeField;
            }
            set
            {
                this.startTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime EndTime
        {
            get
            {
                return this.endTimeField;
            }
            set
            {
                this.endTimeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(DataType = "time", Order = 2)]
        public System.DateTime Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string DisplayTitle
        {
            get
            {
                return this.displayTitleField;
            }
            set
            {
                this.displayTitleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string IsAllDay
        {
            get
            {
                return this.isAllDayField;
            }
            set
            {
                this.isAllDayField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public rootRecurrence Recurrence
        {
            get
            {
                return this.recurrenceField;
            }
            set
            {
                this.recurrenceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public string IsVariance
        {
            get
            {
                return this.isVarianceField;
            }
            set
            {
                this.isVarianceField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public string IsCancelled
        {
            get
            {
                return this.isCancelledField;
            }
            set
            {
                this.isCancelledField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public System.DateTime OriginalStart
        {
            get
            {
                return this.originalStartField;
            }
            set
            {
                this.originalStartField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public string OriginalTimeZone
        {
            get
            {
                return this.originalTimeZoneField;
            }
            set
            {
                this.originalTimeZoneField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootRecurrence
    {

        private string originatingTimeZoneField;

        private sbyte recurrenceTypeField;

        private System.DateTime recurrenceEndDateField;

        private rootRecurrenceReoccursWeekly reoccursWeeklyField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string OriginatingTimeZone
        {
            get
            {
                return this.originatingTimeZoneField;
            }
            set
            {
                this.originatingTimeZoneField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public sbyte RecurrenceType
        {
            get
            {
                return this.recurrenceTypeField;
            }
            set
            {
                this.recurrenceTypeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime RecurrenceEndDate
        {
            get
            {
                return this.recurrenceEndDateField;
            }
            set
            {
                this.recurrenceEndDateField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public rootRecurrenceReoccursWeekly ReoccursWeekly
        {
            get
            {
                return this.reoccursWeeklyField;
            }
            set
            {
                this.reoccursWeeklyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootRecurrenceReoccursWeekly
    {

        private sbyte multipleField;

        private sbyte numOccurencesField;

        private sbyte daysOfWeekField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public sbyte Multiple
        {
            get
            {
                return this.multipleField;
            }
            set
            {
                this.multipleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public sbyte numOccurences
        {
            get
            {
                return this.numOccurencesField;
            }
            set
            {
                this.numOccurencesField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public sbyte DaysOfWeek
        {
            get
            {
                return this.daysOfWeekField;
            }
            set
            {
                this.daysOfWeekField = value;
            }
        }
    }
}
