// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.37595
//    <NameSpace>WSOL.Custom.ContentTypes.Section</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace WSOL.Custom.ContentMaker.Samples.ContentTypes.Section
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class root
    {

        private rich htmlAboveField;

        private rich htmlBelowField;

        private rootSection[] sectionField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public rich HtmlAbove
        {
            get
            {
                return this.htmlAboveField;
            }
            set
            {
                this.htmlAboveField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public rich HtmlBelow
        {
            get
            {
                return this.htmlBelowField;
            }
            set
            {
                this.htmlBelowField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Section", Order = 2)]
        public rootSection[] Section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class rich
    {

        private System.Xml.XmlNode[] anyField;

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
    public partial class aDesignType
    {

        private System.Xml.XmlNode[] anyField;

        private string hrefField;

        private string targetField;

        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order = 0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string href
        {
            get
            {
                return this.hrefField;
            }
            set
            {
                this.hrefField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "NMTOKEN")]
        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootSection
    {

        private string titleField;

        private rootSectionLink linkField;

        private string cssClassField;

        private bool innerWrapField;

        private rootSectionUnit[] unitField;

        public rootSection()
        {
            this.innerWrapField = false;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public rootSectionLink Link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CssClass
        {
            get
            {
                return this.cssClassField;
            }
            set
            {
                this.cssClassField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public bool InnerWrap
        {
            get
            {
                return this.innerWrapField;
            }
            set
            {
                this.innerWrapField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("Unit", Order = 4)]
        public rootSectionUnit[] Unit
        {
            get
            {
                return this.unitField;
            }
            set
            {
                this.unitField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootSectionLink
    {

        private aDesignType aField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public aDesignType a
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootSectionUnit
    {

        private int sizeField;

        private string cssClassField;

        private bool unitPaddingField;

        private rootSectionUnitContentItem[] contentItemField;

        public rootSectionUnit()
        {
            this.sizeField = 1;
            this.unitPaddingField = true;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public int Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string CssClass
        {
            get
            {
                return this.cssClassField;
            }
            set
            {
                this.cssClassField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool UnitPadding
        {
            get
            {
                return this.unitPaddingField;
            }
            set
            {
                this.unitPaddingField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ContentItem", Order = 3)]
        public rootSectionUnitContentItem[] ContentItem
        {
            get
            {
                return this.contentItemField;
            }
            set
            {
                this.contentItemField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootSectionUnitContentItem
    {

        private rootSectionUnitContentItemType typeField;

        private rootSectionUnitContentItemRichText richTextField;

        private rootSectionUnitContentItemContentBlock contentBlockField;

        public rootSectionUnitContentItem()
        {
            this.typeField = rootSectionUnitContentItemType.RichText;
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public rootSectionUnitContentItemType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public rootSectionUnitContentItemRichText RichText
        {
            get
            {
                return this.richTextField;
            }
            set
            {
                this.richTextField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public rootSectionUnitContentItemContentBlock ContentBlock
        {
            get
            {
                return this.contentBlockField;
            }
            set
            {
                this.contentBlockField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public enum rootSectionUnitContentItemType
    {

        /// <remarks/>
        ContentBlock,

        /// <remarks/>
        RichText,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootSectionUnitContentItemRichText
    {

        private rich hTMLField;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public rich HTML
        {
            get
            {
                return this.hTMLField;
            }
            set
            {
                this.hTMLField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class rootSectionUnitContentItemContentBlock
    {

        private long contentIDField;

        private bool contentIDFieldSpecified;

        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public long ContentID
        {
            get
            {
                return this.contentIDField;
            }
            set
            {
                this.contentIDField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContentIDSpecified
        {
            get
            {
                return this.contentIDFieldSpecified;
            }
            set
            {
                this.contentIDFieldSpecified = value;
            }
        }
    }
}
