// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.32989
//    <NameSpace>WSOL.EktronCms.ContentMaker.Samples</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace WSOL.Custom.ContentMaker.Samples.ContentTypes.SiteSettings
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class root {
        
        private rootLogo logoField;
        
        private string logoLinkField;
        
        private rich copyrightTextField;
        
        private ContentIdRefType defaultContentIDField;
        
        private FolderIdRefType defaultFolderIDField;
        
        private string mainMenuIDField;
        
        public root() {
            this.defaultFolderIDField = new FolderIdRefType();
            this.defaultContentIDField = new ContentIdRefType();
            this.copyrightTextField = new rich();
            this.logoField = new rootLogo();
            this.logoLinkField = "/";
            this.mainMenuIDField = "0";
        }
        
        public rootLogo Logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
            }
        }
        
        public string LogoLink {
            get {
                return this.logoLinkField;
            }
            set {
                this.logoLinkField = value;
            }
        }
        
        public rich CopyrightText {
            get {
                return this.copyrightTextField;
            }
            set {
                this.copyrightTextField = value;
            }
        }
        
        public ContentIdRefType DefaultContentID {
            get {
                return this.defaultContentIDField;
            }
            set {
                this.defaultContentIDField = value;
            }
        }
        
        public FolderIdRefType DefaultFolderID {
            get {
                return this.defaultFolderIDField;
            }
            set {
                this.defaultFolderIDField = value;
            }
        }
        
        public string MainMenuID {
            get {
                return this.mainMenuIDField;
            }
            set {
                this.mainMenuIDField = value;
            }
        }
    }
    
    public partial class rootLogo {
        
        private imgDesignType imgField;
        
        public rootLogo() {
            this.imgField = new imgDesignType();
        }
        
        public imgDesignType img {
            get {
                return this.imgField;
            }
            set {
                this.imgField = value;
            }
        }
    }
    
    public partial class imgDesignType {
        
        private string srcField;
        
        private string altField;
        
        private string heightField;
        
        private string widthField;
        
        private ImgAlign alignField;
        
        private bool alignFieldSpecified;
        
        private string borderField;
        
        private string hspaceField;
        
        private string vspaceField;
        
        public string src {
            get {
                return this.srcField;
            }
            set {
                this.srcField = value;
            }
        }
        
        public string alt {
            get {
                return this.altField;
            }
            set {
                this.altField = value;
            }
        }
        
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        public ImgAlign align {
            get {
                return this.alignField;
            }
            set {
                this.alignField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alignSpecified {
            get {
                return this.alignFieldSpecified;
            }
            set {
                this.alignFieldSpecified = value;
            }
        }
        
        public string border {
            get {
                return this.borderField;
            }
            set {
                this.borderField = value;
            }
        }
        
        public string hspace {
            get {
                return this.hspaceField;
            }
            set {
                this.hspaceField = value;
            }
        }
        
        public string vspace {
            get {
                return this.vspaceField;
            }
            set {
                this.vspaceField = value;
            }
        }
    }
    
    public enum ImgAlign {
        
        /// <remarks/>
        top,
        
        /// <remarks/>
        middle,
        
        /// <remarks/>
        bottom,
        
        /// <remarks/>
        left,
        
        /// <remarks/>
        right,
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderIdRefType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ContentIdRefType))]
    public partial class IdRefType {
        
        private string datavalue_idtypeField;
        
        private string datavalue_displayvalueField;
        
        private long valueField;
        
        public string datavalue_idtype {
            get {
                return this.datavalue_idtypeField;
            }
            set {
                this.datavalue_idtypeField = value;
            }
        }
        
        public string datavalue_displayvalue {
            get {
                return this.datavalue_displayvalueField;
            }
            set {
                this.datavalue_displayvalueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public long Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    public partial class FolderIdRefType : IdRefType {
    }
    
    public partial class ContentIdRefType : IdRefType {
    }
    
    public partial class rich {
        
        private List<System.Xml.XmlNode> anyField;
        
        public rich() {
            this.anyField = new List<System.Xml.XmlNode>();
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
    }
    
    public partial class aDesignType {
        
        private List<System.Xml.XmlNode> anyField;
        
        private string hrefField;
        
        private string targetField;
        
        public aDesignType() {
            this.anyField = new List<System.Xml.XmlNode>();
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public List<System.Xml.XmlNode> Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        public string href {
            get {
                return this.hrefField;
            }
            set {
                this.hrefField = value;
            }
        }
        
        public string target {
            get {
                return this.targetField;
            }
            set {
                this.targetField = value;
            }
        }
    }
}
