//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSOL.Custom.ContentMaker.Samples.Views.BlogAuthor {
    
    
    public partial class Default {
        
        /// <summary>
        /// wRenderer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WSOL.ObjectRenderer.WebControls.ObjectRenderer wRenderer;
        
        /// <summary>
        /// rArticleList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WSOL.ObjectRenderer.WebControls.ObjectRenderer rArticleList;
    }
}
